### PR TITLE
allow setting permissions on app install

### PR DESCRIPTION
**Pull request by ewingrj**
allow setting the permissions via the cli when `dao install` is run.

Also changes the default permission manager for `open-permission` to `accounts[0]` instead of `ANY_ENTITY` to enable the permissions to created/revoked after installation. `ANY_ENTITY` is essentially burning the permission manager

### CODE REVIEW

**Comment by sohkai** [comment]
Nice find @perissology!

**Comment by 0x6431346e** [comment]
Oh man... I wish I was aware of this PR :cry:.  Would have solved #297

Related to #337

**Comment by sohkai** [comment]
@0x6431346e Is this still relevant? I remember we had a discussion about permissions, their defaults, and providing a more interactive interface for assigning them.

**Comment by 0xGabi** [comment]
I do think this is still relevant

**Comment by sohkai** [comment]
@0xGabi Were the changes in this PR still relevant?

**Pull request closed without merging**
