### PR TITLE
change help text to not display "aragon" before every command

### LINKED ISSUE #89: APM and DAO entrypoints help shouldn't mention the root aragon tool
When running `dao --help` it shows:

```
aragon dao <command>

Manage your Aragon DAO

Commands:
  aragon dao acl <dao>   Shortcut for aragon dao acl view <dao>
  aragon dao apps <dao>  Get all the apps in a DAO
```

There should be no mention of `aragon dao` just `dao ...`

### PR DESCRIPTION
**Pull request by johnlenin00**
fixes #89

### CODE REVIEW

**Comment by johnlenin00** [comment]
your build bot shows EINTEGRITY error, I think it needs to clear cache?

**Comment by galactusss** [comment]
@johnlenin00 I tested your PR. To been able to merge this changes we need to update yargs to v12, `scriptName` was added on that version. I'll keep testing yargs v12  before merging
Also I added the `usage` function

**Comment by galactusss** [comment]
Related to https://github.com/aragon/aragon-cli/pull/248

**Comment by sohkai** [comment]
@0xGabi It looks like we've updated yargs to v12 now; could we update this and have it merged (or close it if it's already been fixed)?

**Comment by 0xGabi** [comment]
I replace this with #429

**Pull request closed without merging**
