### PR TITLE
Remove js-sha3 dependency (#70)

### PR DESCRIPTION
**Pull request by Kyrrui**

### CODE REVIEW

**Comment by luisivan** [comment]
Hey! Thanks for the PR! There's an issue, and it's that the CLI uses `js-sha3` in many places across its codebase. It would be trivial to replace, since we can have a `sha3(str)` function somewhere as a helper can mimicks the behaviour of `js-sha3`, but just using the compiled implementation `sha3` under the surface

**Comment by Kyrrui** [comment]
@luisivan Ahh didn't realize that, I will go through and refactor. Is there some way to test the CLI so that I can run into this before creating a PR?

**Comment by luisivan** [comment]
Right now there are no tests for the CLI, best we can do is a nice code review and try a few different commands (init, run, etc.)

**Comment by luisivan** [comment]
They behave differently, `sha3` doesn't have a `keccak256` method and it works by updating the hash and then digesting, like this:
```javascript
let d = new SHA3.SHA3Hash();
d.update('foo');
d.digest('hex');
// => "1597842a..."
```
while in `js-sha3` you can just use `keccak256(data)`

**Comment by izqui** [comment]
Is there any reason for changing the module use for `keccak256` hashing?

**Comment by luisivan** [comment]
Mainly performance and not having two different implementations that do the same thing as dependencies

**Comment by Kyrrui** [comment]
Sorry it's taken me so long to get back to this, still planning on doing it. Been busy

**Comment by luisivan** [comment]
Hey @Kyrrui are you still planning on doing this?

**Comment by Kyrrui** [comment]
@luisivan I apologize for the delay - I do plan on doing this, but for now it's on the back-burner for me. Feel free to hand off if it needs to be implemented sooner than later.

**Comment by luisivan** [comment]
No rush for the moment!

**Comment by luisivan** [comment]
Hey @Kyrrui! I take it that you won't take this issue anymore. I'll re-open it and leave unassigned for the moment!

**Pull request closed without merging**
