### PR TITLE
Add husky for pre-commit: lint-stage & pre-push: test

### PR DESCRIPTION
**Pull request by galactusss**
Solve #278 

I checked several commands in a local environment and is working fine.

### CODE REVIEW

**Comment by galactusss** [comment]
@0x6431346e Can you review this when you have time?

**Comment by galactusss** [comment]
Great! Thank you for reviewing it Daniel. I'll take that into account for aragon.js

**Comment by sohkai** [comment]
> Looks like standard and prettier conflicts in regards to comma-dangle and space-before-function-paren, but I guess it's better to keep on par with aragon/aragon.

I think the prettier plugin for eslint should resolve problems like this, if you add it as the last preset? But yes, best to do so and it'll also be easier to publish once we make our shared config available :).

**Comment by 0x6431346e** [comment]
Yes, it does fix it. I only mentioned it because now we're not 100% standard compliant, but I think the trade off is worth it :smile:

**Pull request merged**
