### PR TITLE
Increased test coverage to cli and toolkit packages

### PR DESCRIPTION
**Pull request by ciprian1234**
# 🦅 Pull Request

- Increased test coverage  in package cli:
-- added tests for ipfs start/stop commands
-- added tests for ipfs install/uninstall commands
- Increased test coverage in toolkit:
-- added tests for ipfs/daemon.js
-- added tests for ipfs/config.js
-- added tests for ipfs/misc.js

### CODE REVIEW

**Comment by ciprian1234** [comment]
Flag --serial was added because ava run tests by default in parallel mode, testing of the aragon ipfs start/stop/install/uninstall commands breaks the tests (which run in parallel) that rely on ipfs daemon to be in a different state (stopped or running).
Ava will still run in parallel all tests except the tests which are serial tests. Also we need to make sure to use test.serial() only for the tests which cannot run concurently in order to improve execution time.

**Comment by ciprian1234** [comment]
> Flag --serial was added because ava run tests by default in parallel mode, testing of the aragon ipfs start/stop/install/uninstall commands breaks the tests (which run in parallel) that rely on ipfs daemon to be in a different state (stopped or running).
> Ava will still run in parallel all tests except the tests which are serial tests. Also we need to make sure to use test.serial() only for the tests which cannot run concurently in order to improve execution time.

I have spoken with Daniel about that. I have rewritten the tests, now tests run with a local instance of ipfs, --serial flag is no longer required.

**Comment by ciprian1234** [comment]
> @ciprian1234 thanks for your first contributions and start getting involved with Aragon  The PR is good overall. I fixed some small details that were detected by the linter. For future reference we have a script `npm run lint` that allow you to check those. Also be sure to have husky hooks setup correctly so you run the automated checks on every commit and push.
> 
> Doing:
> 
> ```
> rm -rf .git/hooks/
> npm i -D husky
> ```
> 
> Might help you reset you configuration.

Yep thanks for the tip, I've encountered this issue with husky several times, I guess that's why I forgot to run the linter on last commit.

**Comment by ciprian1234** [comment]
> It seems there are still some issue with the IPFS API on port 8010 that make tests fail. Would you mind take a look. Thanks

I'm going to take a look and fix it.

**Comment by ciprian1234** [comment]
The test failed because a test which should start the ipfs daemon was skipped.

**Comment by macor161** [comment]
Hi @ciprian1234, thanks for the PR it looks great!
However the IPFS tests are currently unstable on the CI, as you can see here: https://github.com/aragon/aragon-cli/pull/1298/checks?check_run_id=439301362
This is why I skipped them in #1427, I should've added a more explicit comment.
Next week I will investigate the problem further.

**Comment by ciprian1234** [comment]
Hi Mathew, I've fixed issue which makes the tests to fail on macOS CI, Now PR branch is up to date and tests are stable on all testing platforms.
Thanks for review and support!

**Comment by 0xGabi** [comment]
This PR improves tests coverage but CI fails sometimes. Until we figure it out this PR will be closed.

**Comment by macor161** [comment]
Closed until we figure out why the CI fails randomly with these tests.

**Pull request closed without merging**
