### PR TITLE
Bundle toolkit compilation output

### PR DESCRIPTION
**Pull request by 0x6431346e**
# 🦅 Pull Request

Currently we are using the toolkit like this:
```
const {
  convertStringToParam,
  encodeParam,
} = require('@aragon/toolkit/dist/acl/params')
```

I think this could be problematic because we can't move files around any longer, if we move a function around the API breaks and we need to push a new major version.

With this change, we are exposing a single module, a large concatenated file, and people then need to use this syntax:

```
const {
  convertStringToParam,
  encodeParam,
} = require('@aragon/toolkit')
```

This gives us freedom over the internal structure of the toolkit.

## ✔️ PR Todo

- [x] Export all functions in `toolkit/src/index.js`
- [x] Include links to related issues/PRs
- [x] Update unit tests for this change
- [x] Update the relevant documentation
- [x] Fix and finish to expose the whole `toolkit` package

### CODE REVIEW

**Comment by 0x6431346e** [comment]
Depends on https://github.com/aragon/aragon-cli/pull/995
Other than that ready to be merged.

**Comment by macor161** [comment]
Nice! 💯

**Comment by ajsantander** [comment]
@0x6431346e can we rebase on develop and make sure all tests are passing before merge?

**Comment by 0x6431346e** [comment]
Thanks @0xGabi for picking this up :heart:

**Pull request merged**
